language: r

r:
  - release
  - devel

deploy.skip_cleanup: true

sudo: required
dist: trusty

cache:
  - packages
  - ccache

latex: false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev
