language: r

r:
  - release
  - devel

deploy.skip_cleanup: true

sudo: required
dist: trusty

cache:
  - packages
  - ccache

latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - libjson-c-dev

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'
